eureka:
  client:
    service-url:
      default-zone: http://eurekaserver:password@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
 application:
    name: UserProfileService
 data:
   mongodb:
     #username: ${MONGO_USER}
     #password: ${MONGO_PASSWORD}
     #database: ${MONGO_DATABASE}
     #port: ${MONGO_PORT}
     #host: ${MONGO_HOST}
     database: userprofile
     port: 27017
     host: localhost
server:
 port: 8084