#spring:
# data:
#   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}

spring:
 application:
  name: NewsSourceService
 data:
   mongodb:     
     database: newssourceservice
     port: 27017
     host: localhost
server:
 port: 8083

 
 eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     #defaultZone: http://localhost:8761/eureka/  
     defaultZone: http://eurekaserver:password@localhost:8761/eureka/